version: "3.8"


services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hiber
      MYSQL_USER: sid
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234



